server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: gb-common
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.yinda.gbcommon.bean
