spring:
  datasource:
    url: jdbc:mysql://13.13.13.29:3306/cattle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/